# This file contains services that can be hosted on the Hetzner box
services:
  # https://caddyserver.com/ - web server and reverse proxy
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./www:/srv/www
      - caddy-data:/data
      - caddy-config:/config

  # https://n8n.io/ - workflow automation
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    env_file: .env
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  caddy-data:
  caddy-config:
  n8n_data:
